version: "3.3"

services:
  pygeoapi:
    container_name: pygeoapi_container
    build:
      context: .
      dockerfile: Dockerfile.pygeoapi_container
    ports:
      - 5000:80
    volumes:
      - ./app:/app

  jupyter:
    container_name: jupyter_container
    build:
      context: .
      dockerfile: Dockerfile.jupyter_container
    ports:
      - "8888:8888"
    volumes:
      - ./app/notebooks:/app/notebooks
    command:
      [
        "jupyter",
        "notebook",
        "--ip=0.0.0.0",
        "--port=8888",
        "--no-browser",
        "--allow-root",
        "--notebook-dir=/app/notebooks",
      ]
