version: "3"
services:
  pygeoapi:
    image: geopython/pygeoapi:latest
    ports:
      - "80:80"
    volumes:
      - ./app:/app
      - ./pygeoapi-config:/pygeoapi/local.config:ro
    command: ["pygeoapi", "run", "--port=80", "--config=/pygeoapi/local.config"]

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    command:
      [
        "jupyter",
        "notebook",
        "--ip=0.0.0.0",
        "--port=8888",
        "--no-browser",
        "--allow-root",
        "--notebook-dir=/app",
      ]
